### ISSUE TITLE
URL Manager - Unable to edit webhook

### ISSUE THREAD

**Issue by iengineer** [tnware/product-checker#2]
Unable to change webhook when editing setting #2

Troubleshooting:
- cleared all webhooks, tried uppercase, mix cased and lower cased webhook names _(example: "Webhook", "webhook", "WEBHOOK")_
- reinstalled app, used the default webhook_1, added my URL there
- git pulled to make sure on latest version

Following error appears anytime you click "ok" after selecting a webhook destination:

```
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\product-checker-master\product_settings.py", line 166, in update
    url = listbox.GetString(url_key)
wx._core.wxAssertionError: C++ assertion ""IsValid(n)"" failed at ..\..\src\msw\listbox.cpp(450) in wxListBox::GetString(): invalid index in wxListBox::GetString
```

Does not matter what I do, anytime I click "Ok" that error spams in the command prompt.

**Comment by tnware** [comment]
if you are getting this error make sure to select the webhook from the list before you try to click the “configure” button.

**Comment by tnware** [comment]
This will no longer be an issue in future releases. I made a handler to output a message that will explain how to fix this to the user.

![image](https://user-images.githubusercontent.com/537897/80851532-fdcd0700-8be7-11ea-9968-6d5b4c0cba27.png)
