### ISSUE TITLE
Error when parsing Amazon

### ISSUE THREAD

**Issue by pr110** [tnware/product-checker#3]
I'm not sure if this is due to an issue with Amazon's support on monitoring, but the links don't parse.

**Comment by pr110** [comment]
Also, It reads Walmart URL detected twice, but it skips over one of the two links I have set up.

**Comment by tnware** [comment]
try updating to the latest version to resolve amazon issues. you must have a bad Walmart link but I don’t have enough information to say.

**Comment by pr110** [comment]
How do you recommend updating? I zip installed it to begin with not git clone.

**Comment by pr110** [comment]
I'd like to add this. It was received after updating the app.py file.
app.py:74: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=driver_path, chrome_options=options)
Although it seems that it does now check Amazon listings successfully.

**Comment by tnware** [comment]
these warnings are harmless to the functionality and are only important to maintaining the codes functionality. i should be able to address this sometime in the future but for now my selenium code is using the deprecated chrome_options
